@file:Suppress("RedundantVisibilityModifier","RedundantUnitReturnType","RemoveRedundantQualifierName","unused","UnusedImport","ClassName","REDUNDANT_PROJECTION","DEPRECATION")

package cloudshift.awscdk.dsl.services.inspector

import cloudshift.awscdk.common.CdkDslMarker
import kotlin.Any
import kotlin.Number
import kotlin.String
import kotlin.collections.Collection
import kotlin.collections.MutableList
import software.amazon.awscdk.IResolvable
import software.amazon.awscdk.services.inspector.CfnAssessmentTemplateProps

@CdkDslMarker
public class CfnAssessmentTemplatePropsDsl {
  private val cdkBuilder: CfnAssessmentTemplateProps.Builder = CfnAssessmentTemplateProps.builder()

  private val _rulesPackageArns: MutableList<String> = mutableListOf()

  private val _userAttributesForFindings: MutableList<Any> = mutableListOf()

  /**
   * @param assessmentTargetArn The ARN of the assessment target to be included in the assessment
   * template. 
   */
  public fun assessmentTargetArn(assessmentTargetArn: String) {
    cdkBuilder.assessmentTargetArn(assessmentTargetArn)
  }

  /**
   * @param assessmentTemplateName The user-defined name that identifies the assessment template
   * that you want to create.
   * You can create several assessment templates for the same assessment target. The names of the
   * assessment templates that correspond to a particular assessment target must be unique.
   */
  public fun assessmentTemplateName(assessmentTemplateName: String) {
    cdkBuilder.assessmentTemplateName(assessmentTemplateName)
  }

  /**
   * @param durationInSeconds The duration of the assessment run in seconds. 
   */
  public fun durationInSeconds(durationInSeconds: Number) {
    cdkBuilder.durationInSeconds(durationInSeconds)
  }

  /**
   * @param rulesPackageArns The ARNs of the rules packages that you want to use in the assessment
   * template. 
   */
  public fun rulesPackageArns(vararg rulesPackageArns: String) {
    _rulesPackageArns.addAll(listOf(*rulesPackageArns))
  }

  /**
   * @param rulesPackageArns The ARNs of the rules packages that you want to use in the assessment
   * template. 
   */
  public fun rulesPackageArns(rulesPackageArns: Collection<String>) {
    _rulesPackageArns.addAll(rulesPackageArns)
  }

  /**
   * @param userAttributesForFindings The user-defined attributes that are assigned to every finding
   * that is generated by the assessment run that uses this assessment template.
   * Within an assessment template, each key must be unique.
   */
  public fun userAttributesForFindings(vararg userAttributesForFindings: Any) {
    _userAttributesForFindings.addAll(listOf(*userAttributesForFindings))
  }

  /**
   * @param userAttributesForFindings The user-defined attributes that are assigned to every finding
   * that is generated by the assessment run that uses this assessment template.
   * Within an assessment template, each key must be unique.
   */
  public fun userAttributesForFindings(userAttributesForFindings: Collection<Any>) {
    _userAttributesForFindings.addAll(userAttributesForFindings)
  }

  /**
   * @param userAttributesForFindings The user-defined attributes that are assigned to every finding
   * that is generated by the assessment run that uses this assessment template.
   * Within an assessment template, each key must be unique.
   */
  public fun userAttributesForFindings(userAttributesForFindings: IResolvable) {
    cdkBuilder.userAttributesForFindings(userAttributesForFindings)
  }

  public fun build(): CfnAssessmentTemplateProps {
    if(_rulesPackageArns.isNotEmpty()) cdkBuilder.rulesPackageArns(_rulesPackageArns)
    if(_userAttributesForFindings.isNotEmpty())
        cdkBuilder.userAttributesForFindings(_userAttributesForFindings)
    return cdkBuilder.build()
  }
}
