@file:Suppress("RedundantVisibilityModifier","RedundantUnitReturnType","RemoveRedundantQualifierName","unused","UnusedImport","ClassName","REDUNDANT_PROJECTION","DEPRECATION")

package cloudshift.awscdk.dsl.services.sagemaker

import cloudshift.awscdk.common.CdkDslMarker
import kotlin.String
import software.amazon.awscdk.services.sagemaker.CfnModelPackage

@CdkDslMarker
public class CfnModelPackageMetadataPropertiesPropertyDsl {
  private val cdkBuilder: CfnModelPackage.MetadataPropertiesProperty.Builder =
      CfnModelPackage.MetadataPropertiesProperty.builder()

  /**
   * @param commitId The commit ID.
   */
  public fun commitId(commitId: String) {
    cdkBuilder.commitId(commitId)
  }

  /**
   * @param generatedBy The entity this entity was generated by.
   */
  public fun generatedBy(generatedBy: String) {
    cdkBuilder.generatedBy(generatedBy)
  }

  /**
   * @param projectId The project ID.
   */
  public fun projectId(projectId: String) {
    cdkBuilder.projectId(projectId)
  }

  /**
   * @param repository The repository.
   */
  public fun repository(repository: String) {
    cdkBuilder.repository(repository)
  }

  public fun build(): CfnModelPackage.MetadataPropertiesProperty = cdkBuilder.build()
}
