name: Dependabot auto-approve
on: pull_request

permissions:
  pull-requests: write
  contents: write

# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      # https://github.com/dependabot/fetch-metadata
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: "dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b" # v2.4.0

      - name: Automatically approve & merge Dependabot patch PRs
        if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ github.token }}
